### ISSUE TITLE
Make available for commonJs

### ISSUE THREAD

**Issue by hamishjohnson** [wooorm/franc#102]
The `require`ment that we are forced to use es modules means that I can't use it with ts-node and typescript

**Comment by wooorm** [comment]
Please read the linked guide in both the readme and the changelog on ways to handle ESM (one solution is to stay on the previous version for now).
ts-node has ESM support: https://github.com/TypeStrong/ts-node#experimental-esm-support

**Comment by qertis** [comment]
+1. Cannot make available for cjs use parcel build
