### ISSUE TITLE
How to generate data.js in franc packages

### ISSUE THREAD

**Issue by vuongnv-0085** [wooorm/franc#104]
Hi @wooorm, Thanks for create greate packages
I have a question: How to generate https://github.com/wooorm/franc/blob/main/packages/franc/data.js file ?
Can you tell me the way to do it ? Where the data base is also OK 🙇 

Thanks

**Comment by gaborcsardi** [comment]
I would try 
```
npm run build-packages
```
Cf. https://github.com/wooorm/franc/blob/ee64d1ffd9d83c3cc8a4cd76cfaa063d1bec24d6/package.json#L44-L52

**Comment by wooorm** [comment]
Yup, as Gábor explains, use the npm scripts!
