### ISSUE TITLE
Package update for 5.0.0

### ISSUE THREAD

**Issue by 5d-jh** [wooorm/franc#105]
My project, which is unable to update to version 6.0.0, is facing security vulnerability right now. Is there any plans to release 5.0.1 with dependency update?

**Comment by wooorm** [comment]
Hey!

- You can switch your project to ESM, which I recommend, although I understand you can’t do it now.
- There is no vulnerability in `5.0.1`. GitHub and npm are lying. See for example https://overreacted.io/npm-audit-broken-by-design/. I recommend ignoring it.
- As it isn’t really a problem, I don’t see a reason to “fix” it
