### ISSUE TITLE
Problem to detect language

### ISSUE THREAD

**Issue by corsaronero** [wooorm/franc#109]
Hi 
i would like to integrate this library, i tried to do some tests but it doesn't seem to answer right
example:
ITALIAN: domani torno a casa,                answer: hau  Hausa	= 1  Portuguese  = 0.9379579872984856

POLISH :  witam serdecznie, teraz zaczynamy       answer: Portuguese  : 1

Spanish : Trabajo en la escuela. Soy profesor.      answer: Esperanto 1

English: write some text   Norvegian 1, Balcan 0.99   etc......

why doesn't it recognize languages? do I do something wrong?

Thanks

**Comment by wooorm** [comment]
See https://github.com/wooorm/franc#whats-not-so-cool-about-franc and other closed issues!

**Comment by corsaronero** [comment]
I m already see the link, i m using this for testing https://wooorm.com/franc/
can you explain why the result it is not good?
Thanks

**Comment by wooorm** [comment]
Read the text. Your inputs are too small.

**Comment by corsaronero** [comment]
ok thanks!

but still for some sentence example this :  What do we know so far about the Covid-19 variants?   the answer it is Scots and not English

**Comment by wooorm** [comment]
The reason is: machine learning. It’s a guess. A probability.
