### ISSUE TITLE
Inaccurate detection examples

### ISSUE THREAD

**Issue by demisx** [wooorm/franc#16]
Here are just a few inaccuracies I've come across testing this package:

```js
franc('iphone unlocked') // returns 'ibb' instead of 'eng'
franc('new refrigerator') // returns 'dan' instead of 'eng'
franc('макбук копмьютер очень хороший') // returns 'kir' instead of 'rus'
```

**Comment by wooorm** [comment]
Right, that's true. And there are many more (for example, see #8, and the [Hackernews thread](https://news.ycombinator.com/item?id=8404978).

This is a trade-off: accuracy v.s. amount of supported languages; I opt for the latter.

If you'd like higher accuracy, I suggest using the 'whitelist' and 'blacklist' feature, the version of franc with support for 75 languages, or creating a fork with even less supported languages.

Success!

**Comment by demisx** [comment]
You are right. Narrowing down languages by whitelisting only those that you need to support does improve the recognition quality.

**Comment by demisx** [comment]
Can I assume that returned 3 letter language codes are http://en.wikipedia.org/wiki/ISO_639-2?

**Comment by wooorm** [comment]
Close, they're [iso-638-3](https://github.com/wooorm/iso-639-3)!

**Comment by demisx** [comment]
:+1: Thank you so much for such prompt responses. We are going to be using your library in our project.

**Comment by wooorm** [comment]
Cool! I'd love to hear more from the project (maybe through e-mail?), or let me know if you have more questions.
