### ISSUE TITLE
How to improve single word detection with limited list of supported languages

### ISSUE THREAD

**Issue by demisx** [wooorm/franc#17]
Hello again.
I currently have this:

```js
var q = 'отличный';
var guessedLanguageCode = franc(q, {
    whitelist: ['eng', 'rus', 'spa']
}); // <- returns `und`
```

In this particular case, `q` contains letters that clearly are not part of neither the English, nor Spanish alphabet. Nevertherless, `franc` returns `und`.  Is there any way to improve detection of single words when there is just a handful of languages we need to support?

**Comment by wooorm** [comment]
Currently, not really: I think though, the length is calculated before trimming white space, thus adding spaces might fool my limit ;)

What about a real solution, probably through an option, what could that look like?

**Comment by demisx** [comment]
:+1: `minLength` works! Thank you so much. Off the topic, is there any reason you surround the javascript object keys with single quotes? E.g.

```js
franc('the', { 'minLength': 3 })
```

Why not simply:

```js
franc('the', { minLength: 3})
```

**Comment by wooorm** [comment]
Please direct any further question not directly related to franc to my e-mail; but it has to do with code style: better all keys quoted than some, IMHO.
