### ISSUE TITLE
Support ISO 639-1 codes alongside ISO 639-3

### ISSUE THREAD

**Issue by dparnane** [wooorm/franc#19]
The two-letter ISO 639-1 codes are quite widely used, for example in MongoDB's text index. Are there plans for adding support for this language code variant in the future?

Mapping between the two is trivial as a post-process, but creates unnecessary clutter whereas getting the desired language code variant straight from Franc would be very neat and tidy.

**Comment by wooorm** [comment]
No, there plans, because many supported languages do not have a 639-1 code.

P.S. See GH-10.
