### ISSUE TITLE
How to contribute languages

### ISSUE THREAD

**Issue by smari** [wooorm/franc#24]
Hi! I'm curious to know how to contribute new languages to franc? Do you have a standard method for creating the definition lines?

**Comment by wooorm** [comment]
Contact the Unicode Consortium: http://unicode.org/udhr/contributing.html. It’ll probably take years though.

Out of curiosity, which language would you like to add? (Does it have an [Ethnologue](http://www.ethnologue.com) entry?)

**Comment by smari** [comment]
I'd like to add Icelandic (which I have the knowledge to do), but I'm also looking for support for Georgian.

(For fun: I just threw this together -- probably not useful for most people, but it's useful for my purposes and others might benefit too: https://github.com/occrp/Francserver )

**Comment by wooorm** [comment]
Icelandic is supported in he `franc-all` version, as it has ± 300,000 speakers. Read [this](https://github.com/wooorm/franc#supporting-more-or-less-languages) for more info on how to include it.

Also, cool server! :+1:

**Comment by smari** [comment]
Ah, thanks for that. How would I use that from node though?

**Comment by wooorm** [comment]
I believe the file supports CommonJS so you should be able to load the file directly. Otherwise, [forking](https://github.com/wooorm/franc#supporting-more-or-less-languages).
