### ISSUE TITLE
Wrong language detection even for simple texts

### ISSUE THREAD

**Issue by snow01** [wooorm/franc#26]
I was using franc in my project, but just to discover it is detecting wrong language even for simple texts --

$ franc "Red Deer stags relaxing at sunrise"
dan

While https://github.com/dachev/node-cld and google language detects it correctly --

{ reliable: true,
  languages: [ { name: 'ENGLISH', code: 'en', percent: 97, score: 1152 } ],
  chunks: [ { name: 'ENGLISH', code: 'en', offset: 0, bytes: 39 } ] }

Text is from - https://www.flickr.com/photos/jellybeanzgallery/23287127571/in/explore-2015-11-28/

**Comment by wooorm** [comment]
Thanks for the Q, @snow01!

This problem is already addressed in #8, #16, and #23. It’s a trade-off between more languages or higher reliability. Franc opts for the first.
