### ISSUE TITLE
I got NaN when runinng franc.all

### ISSUE THREAD

**Issue by moshest** [wooorm/franc#29]
I run the following code:

    franc.all('פאר טסי', {minLength: 3})
    // result: [ [ 'heb', NaN ], [ 'ydd', NaN ] ]

Why I got `NaN`? Any quick fix?

**Comment by wooorm** [comment]
Quick fix would be to treat `NaN` as `0`.

**Comment by moshest** [comment]
I did this hack:

    franc.all(tran, FRANC_OPTIONS).forEach(function (item, i) {
      // FIXME remove this hack
      if (isNaN(item[1])) item[1] = 0.01 / i;
    });

**Comment by wooorm** [comment]
Published as `1.1.3`!

**Comment by moshest** [comment]
Saw your fix. Thanks.

In this case, `"heb"` is better suggestion over `"ydd"` and it's reasonable to suggest `"heb"` over `"ydd"`.
I think it's wrong to give both of them the same result. Am I right?

**Comment by wooorm** [comment]
From your human view, and familiarity with both languages, it is, but from franc’s, a humble machine, it is not. See GH-8, GH-16, GH-23, GH-27.

**Comment by moshest** [comment]
OK. Thanks!
