### ISSUE TITLE
Readme with death sign

### ISSUE THREAD

**Issue by rugk** [wooorm/franc#32]
Do you really have to use `†` in your Readme. It's Christian and (also) is a symbol for death, so it is probably not the best idea to use it there.
There are better Unicode characters... :smiley:

**Comment by wooorm** [comment]
And It’s also a roasting spit! (yes, really!)

Haha, well, it’s pretty standard fwiw: https://en.wikipedia.org/wiki/Note_(typography) (I think I actually used that list at the time I wrote this).

Thanks, but as it’s so standard, I’d rather keep this as-is.

**Comment by rugk** [comment]
And [here](https://en.wikipedia.org/wiki/Dagger_(typography)#Modern_usage):
> The dagger is usually used to indicate a footnote if an asterisk has already been used

**Comment by rugk** [comment]
BTW actually it is not really the Christian cross character, Unicode has a separate one for this:
> Used in these contexts, the dagger glyph is a stand-in for the Christian cross symbol. Note, however, that Unicode defines a separate "Latin cross" character (✝, U+271D)

Another quote:
> While daggers are freely used in English-language texts,[citation needed] they are often avoided in other languages because of their similarity to the Christian cross. In German, for example, daggers are commonly employed only to indicate a person's death or the extinction of a word, language, species or the like.

**Comment by wooorm** [comment]
Oh you’re right, funky! Well, that makes it less bad haha. And I don’t really think it’s worth a commit.

I’m guessing that at the time (https://github.com/wooorm/franc/commit/6166cf89f8aa0291d41a1af0a643eb8bb6e27c15#diff-1e290ac8433d555bce009b162cb869d0), I didn’t know how to escape an asterisk in markdown!
