### ISSUE TITLE
Numbers of speakers outdated

### ISSUE THREAD

**Issue by rugk** [wooorm/franc#33]
[Currently](http://www.statista.com/statistics/266808/the-most-spoken-languages-worldwide/) Hindi is on the 2nd place of the native speakers and not Spanish. On the third place there is English and on the fourth Spanish.

Of course could could also change the numbers to show the total speakers of the language (and not the native ones).

**Comment by wooorm** [comment]
Thanks for letting me know! If you’d like, [speakers](https://github.com/wooorm/speakers) is the correct place to change that info. I’d rather not use this data in speakers though: using different datasets makes the numbers rather unreliable.

This info is pretty meaningless for franc too, as franc uses it to determine which languages are included in the [browser builds](https://github.com/wooorm/franc#browser), and Hindi and Spanish will both be in every pre-built distribution whether the data is updated or not.

If you can find some source, other than OHCHR, which has as many or more languages I’d love to incorporate newer numbers though!
