### ISSUE TITLE
Why Chinese is cmn and not chi?

### ISSUE THREAD

**Issue by intergleam** [wooorm/franc#37]
According to standards Chinese should be `chi` but the library detects it as `cmn`

**Comment by wooorm** [comment]
Which standards? `cmn` is ISO 639-3.

**Comment by intergleam** [comment]
http://www.w3schools.com/tags/ref_language_codes.asp

**Comment by intergleam** [comment]
and http://loc.gov/standards/iso639-2/ISO-639-2_utf-8.txt

**Comment by intergleam** [comment]
I need to match them with lang attribute codes

**Comment by wooorm** [comment]
That seems to be ISO 639-1, which doesn’t have all codes for languages supported by franc.

Also: w3schools is a [terrible](http://www.w3fools.com) [source](http://meta.stackoverflow.com/questions/280478/why-not-w3schools-com).

> I need to match them with lang attribute codes

Use ISO 639-3.

**Comment by intergleam** [comment]
this is crazy it is 800KB minified https://github.com/wooorm/iso-639-3/releases. Where can I get a list of only those used in franc-most.js? Thanks

**Comment by wooorm** [comment]
If you’re worried about size, I don’t suggest using `franc-most`.

800kb is rather large, because it encompasses more information than you need (btw, GZip make it 75kB)

Here’s the list of currently detected languages in the `most` bundle:

```txt
abk
ace
acu
ada
afr
agr
ajg
aka
als
alt
amc
ame
amh
amr
arb
arl
arn
ast
ayr
azj
azj
bam
ban
bba
bci
bcl
bel
bem
bfa
bho
bin
bis
boa
bod
bos
bos
bre
bug
bul
cab
cak
cat
cbr
cbt
cbu
ceb
ces
cha
chj
chk
cic
cjk
cjs
ckb
cnh
cni
cof
cos
cot
cpu
crs
csa
csw
ctd
cym
dag
dan
ddn
deu
dga
dip
dyo
dyu
emk
eng
epo
est
eus
eve
evn
ewe
fao
fij
fin
fon
fra
fur
gaa
gag
gax
gjn
gkp
gla
gle
glg
guc
gug
guu
gyr
hat
hau
haw
hea
heb
hil
hin
hlt
hms
hna
hni
hrv
hsb
hun
hus
huu
ibb
ibo
ike
ilo
ind
isl
ita
jav
jiv
kal
kaz
kbp
kde
kea
kek
kha
khk
kin
kir
kjh
kmb
knc
kng
koi
koo
kqn
kri
krl
kwi
lad
lav
lia
lin
lit
lns
lob
lot
loz
ltz
lua
lue
lug
lun
lus
mad
mag
mah
mai
mam
mar
maz
mcd
mcf
men
mic
min
miq
mkd
mlt
mos
mri
mxi
mxv
mzi
nav
nba
nbl
ndo
nds
nep
nhn
nio
njo
nld
nno
nob
not
nso
nya
nym
nyn
nzi
ojb
oss
ote
pam
pau
pbb
pcd
pes
pis
plt
pol
pon
por
pov
ppl
quc
qud
qug
quy
quz
qva
qvc
qvh
qvm
qvn
qwh
qxa
qxn
qxu
rar
rgn
rmn
rmy
roh
ron
run
rus
sag
sah
san
sco
shk
shp
skr
slk
slv
sme
smo
sna
snk
snn
som
sot
spa
src
srp
srp
srr
ssw
suk
sun
sus
swb
swe
swh
tah
tat
tbz
tca
tem
tet
tgk
tgl
tir
tiv
tob
toi
toj
ton
top
tpi
tsn
tso
tsz
tuk
tuk
tur
tyv
tzm
uig
uig
ukr
umb
ura
urd
uzn
uzn
ven
vep
vie
vmw
war
wln
wol
wwa
xho
xsm
yad
yao
yap
ydd
ykg
yor
yua
zam
ztu
zul
```

**Comment by intergleam** [comment]
but ho can i get JSON to match the 2-letter code? Should I do it myself?

**Comment by wooorm** [comment]
Yup, that’s outside the scope of this project, but it would be useful if someone created a list of such mapping (see GH-30). Note however that many of the languages listed above do not have two-letter codes.
