### ISSUE TITLE
npm versions of franc-all and franc-most?

### ISSUE THREAD

**Issue by knod** [wooorm/franc#43]
I'd like to use franc-most or franc-all in a project, but if I can't use `npm install` and my package.json, it makes the project more difficult to work with and more difficult to collaborate on. I wasn't able to find them on npmjs.org. Are these available under a different name?

**Comment by wooorm** [comment]
You’re right!

I’ve just rewritten the project so that the different packages will be published to npm.
In a minute or so, I’ll release them!
