### ISSUE TITLE
152 languages with npm, not 175

### ISSUE THREAD

**Issue by knod** [wooorm/franc#44]
I may be counting wrong, but in data.json, there appear to be around 152 languages, not the 175 languages the README describes. Was that number an approximation?

**Comment by wooorm** [comment]
There’s also [`expressions.js`](https://github.com/wooorm/franc/blob/45482a80634f595c460c097b7347c9db190e6959/lib/expressions.js), which contains other languages: some scripts only come with one associated language, so we don‘t need trigrams in `data.json`.
