### ISSUE TITLE
Greek (~13 million speakers) not supported in npm franc

### ISSUE THREAD

**Issue by knod** [wooorm/franc#45]
I couldn't find greek in the data.json of the the npm version of franc, despite the fact that searches indicate that it has more than 13 million speakers. Did I miss it somewhere?

**Comment by wooorm** [comment]
Greek is called `ell`, and lives in [`expressions.js`](https://github.com/wooorm/franc/blob/45482a80634f595c460c097b7347c9db190e6959/lib/expressions.js#L21).
