### ISSUE TITLE
Almost got it right in one of the examples

### ISSUE THREAD

**Issue by joakim** [wooorm/franc#46]
franc('Alle mennesker er født frie og'); //=> 'nno'

This is actually `nob` (Norwegian Bokmål), not `nno` (Norwegian Nynorsk) :)

If you finish the sentence it gets it right.

    franc('Alle mennesker er født frie og med samme menneskeverd og menneskerettigheter.'; //=> 'nob'

Still, great library!

**Comment by wooorm** [comment]
Thanks @joakim. Do you happen to know what the correct Nynorsk would be?

**Comment by joakim** [comment]
Sure!

> Alle menneske er fødde til fridom og med same menneskeverd og menneskerettar.

Source: https://it.wikipedia.org/wiki/Lingua_norvegese

**Comment by wooorm** [comment]
Cheers, @joakim 🎉

**Comment by kaareal** [comment]
Also perfectly valid danish, so perhaps not the best example
