### ISSUE TITLE
Could latin be added?

### ISSUE THREAD

**Issue by enjikaka** [wooorm/franc#49]
Here's a set of latin text you could use; http://runeberg.org/olmagnus/

**Comment by wooorm** [comment]
Hi!

It’s already available, in the [`franc-all`](https://github.com/wooorm/franc/tree/master/packages/franc-all#support) package.

**Comment by enjikaka** [comment]
@wooorm Cool. Didn't work on the website, http://wooorm.com/franc/ , so figured it wasn't in.

**Comment by wooorm** [comment]
Correct, it’s not on the site, that’d be a bit big. If you want to work on it, I’m open to a PR!
