### ISSUE TITLE
Possible on streaming data?

### ISSUE THREAD

**Issue by ImSuriya** [wooorm/franc#51]
Hi, 
first of all thanks for sharing such a nice tool.
I'd like to ask know like is that possible to use this get accurate date from twitter streaming api using nodejs.

the app am creating let the people to get trusted data about politics. currently am getting some few datas with accuracy from retweets only but i would like to get more accurate data from raw streaming tweets.

am streaming datas based on tracking some keywords 
for example if i said "track : donald trump " this will give realtime tweets about trump. but the problem is its also returns some unwanted funny quotes, mime etc. i just want to have exact tweets for the purpose.

many thanks for any help and thanks again for this tool

**Comment by wooorm** [comment]
Hi @ImSuriya! 👋

Thanks for your interest in franc, and thanks for the kind words! Yes, it’s possible to use franc together with the twitter streaming api.

However, your question seems to be about an entirely different topic, unrelated to franc. franc does language detection, you’re asking for something else, and I can’t help you with that.
