### ISSUE TITLE
Using franc in the browser?

### ISSUE THREAD

**Issue by TangSteven** [wooorm/franc#53]
How would you use franc without npm in the browser, and also how does one turn the 3 letter language code into the full name of the language as seen in the demo?

**Comment by wooorm** [comment]
Hi Tang 👋

Info on how to use franc in the browser is in the [installation section](https://github.com/wooorm/franc#installation).

The demo uses [`iso-639-3`](https://github.com/wooorm/iso-639-3). We had some discussions earlier here on the issues about those. You can search for that here to find more on language codes.

**Comment by TangSteven** [comment]
Thanks.
