### ISSUE TITLE
Czech language detection is not accurate

### ISSUE THREAD

**Issue by astoilkov** [wooorm/franc#56]
Results from `franc().all()` are returning the wrong order of languages. I tried some online language detection tools (also Google Translate) - they all correctly recognize this is Czech.

> já tenhle týden dopíšu, nahodím na Intercom Educate (pořídil jsem minulý týden) a bude to na první uživatele

**Comment by astoilkov** [comment]
I use `franc-min` btw.

**Comment by wooorm** [comment]
Hi! See <https://github.com/wooorm/franc#whats-not-so-cool-about-franc>. For smaller samples and less supported languages you may like [`node-cld`](https://github.com/dachev/node-cld).
