### ISSUE TITLE
Wrong translations

### ISSUE THREAD

**Issue by syzer** [wooorm/franc#57]
1. I like this package.
2. I know its a port.
3. But how come `franc('what up') === 'deu'`

**Comment by syzer** [comment]
also 'one way ticket' is hilarious :D

**Comment by webappster** [comment]
I noticed this too.... of course not exactly syzer's examples, but many others. :disappointed: 

To name one, this is the result from _franc-min_ for the phrase _'Such a nice script!'_:
> 0: (2) ["ron", 1]
1: (2) ["ces", 0.7406372275013975]
2: (2) ["hau", 0.7294577976523198]
3: (2) ["srp", 0.6880939072107323]
4: (2) ["deu", 0.6690888764673002]
5: (2) ["eng", 0.6662940190050308]
...

**Comment by webappster** [comment]
Ok, I spotted [this post from wooorm](https://github.com/wooorm/franc/issues/56#issuecomment-358665631) and it seems that franc just isn't the right tool for our short phrases.

Well, I just missed that line in the readme:
> franc supports many languages, so make sure to pass it big documents, to get reliable results.

**Comment by wooorm** [comment]
Basically https://github.com/wooorm/franc#whats-not-so-cool-about-franc!

Thanks for spotting it @webappster 😉

**Comment by syzer** [comment]
@webappster what languages you need for short phases ?
