### ISSUE TITLE
ISO-639-1 codes

### ISSUE THREAD

**Issue by thiagodp** [wooorm/franc#61]
Hello, first of all thanks for this great project!
Since Franc appears to use ISO-639-3 codes (right?), I was wondering if it can also return ISO-639-1 codes.
If it can't, I think it may worth it to create a section like *See Also* in README.md with some libraries that may help with that, such as [nodejs-langs](https://github.com/adlawson/nodejs-langs). For instance:
```js
var franc = require( 'franc' );
var langs = require('langs');
var iso_639_3 = franc('O Brasil caiu 26 posições' );
langs.where( "3", iso_639_3 );
// { '1': 'pt', '2': 'por', '3': 'por', name: 'Portuguese', local: 'Português', '2T': 'por','2B': 'por' }
```

**Comment by brettimus** [comment]
Good tip 😁 . I opened a PR as thanks, this was helpful for me

**Comment by thiagodp** [comment]
@brettimus Thank you! ;)

**Comment by amitbend** [comment]
I made a new slim package to convert between iso-639-3 to iso-639-1, For languages without iso-639-1 that have a "macro language".
PR are welcome!
[iso-639-3-to-1 package](https://www.npmjs.com/package/iso-639-3-to-1)
