### ISSUE TITLE
Add Words to a certain language

### ISSUE THREAD

**Issue by tomerb15** [wooorm/franc#64]
Amazing project! Really, I'm not just flattering :)
I was wondering if there is a possibility to add certain words to certain languages on the fly?
Teaching Franc more things on the fly.

**Comment by wooorm** [comment]
@tomerb15 Thank you!

That’s going to be very hard. The three franc’s are built from several sources. The code is generated on publish time by the code in this repo. So though the code to do that is in this repo, the runtime library doesn’t support it.

**Comment by tomerb15** [comment]
Thanks for the explanation.
The advantages and options are endless if Franc will be able to learn stuff.

For my project, there are many words and sentences that are being identified as English instead of Portuguese and vise versa, if i can't prevent the next time it happens, i can't use this awesome lib.

**Comment by wooorm** [comment]
> For my project, there are many words and sentences that are being identified as English instead of Portuguese and vise versa, if i can't prevent the next time it happens, i can't use this awesome lib.

Just adding words won’t work. That’s not how franc works. It takes a different approach, and this is one of the [“not so cool parts”](https://github.com/wooorm/franc#whats-not-so-cool-about-franc) of franc. For less languages but smaller inputs, I believe you’ll fare better using [cld](https://github.com/dachev/node-cld).
