### ISSUE TITLE
The Kabyle [kab] language.

### ISSUE THREAD

**Issue by anzart** [wooorm/franc#74]
The [Kabyle [kab]](https://iso639-3.sil.org/code/kab)  language is not in the list of supported languages, how can I add it? thank you for your help!

**Comment by wooorm** [comment]
Adding languages is unfortunately extremely difficult. You can add a language by adding a UDHR in that language. The steps are laid out here: http://unicode.org/udhr/contributing.html. It’ll probably take years though.

**Comment by ghost** [comment]
Hi @wooorm @anzart 
Please find a UDHR version in kabyle language in my Gitlab repo. The raw text is extracted from the UDHR version submitted by Algeria to United Nations.

The original version of the PDF is in the same repo :

https://gitlab.com/imsidag/corpora

Original source UN : https://algeria.un.org/fr/36772-declaration-universelle-des-droits-de-lhomme-trilingue

Even if the PDF in the UN website says « Arabic », the PDF contains inside a kabyle version.

**Comment by wooorm** [comment]
Hi! Things are generated in this project (see the code). Not from PDFs: from actual unicode characters. If it is upstream, it will be here.

**Comment by ghost** [comment]
Thank you @wooorm 

I have clean set of data about Kabyle `kab` language in raw text (approx 1 million sentences) and I want to create the profile for my language by myself.

From where to start?

**Comment by wooorm** [comment]
This project pulls in from upstream sources; you have to get it in those sources. It has to be published as Kabyle by OHCHR/UN first.

**Comment by ghost** [comment]
Thank you @wooorm 
I'll contact the OHCHR/UN  to tell them to add it 👍

**Comment by ghost** [comment]
Hello @wooorm @anzart

I wrote a request to the OHCHR and I've pointed out that the **Kabyle translation** published by the Algerian official section at the UN (as mentionned above) is missing from the UN OHCHR Library.

The UDHR Team answer :

```
Dear,

Many thanks for sharing us the information.

The Kabyle version of the UDHR will be made available soon in the collection.

Best,
UDHR team
```

Once published, I'll be back to this thread.

P.S. : Eric Muller accepter to add UDHR in Kabyle. See https://github.com/eric-muller/udhr/commit/e6cd5f653c8c77150f8a08083e5256f08c73fafe

Regards,

**Comment by wooorm** [comment]
Cool!

**Comment by ghost** [comment]
Hi @wooorm @anzart 

The UDHR team of the UHCHR has just Added the UDHR in kabyle but they've added the trilingual PDF that I've mentionned to them. May be they don't know how to extract the Kabyle version in raw text (Unicode UTF-8) like I did in my repo.

Link : https://www.ohchr.org/en/human-rights/universal-declaration/translations/kabye-0

Link to my repo : https://gitlab.com/imsidag/corpora

**Comment by Mejans** [comment]
Hello @wooorm 
any news for this issue?
I saw a lot happened recently on https://github.com/eric-muller/udhr/
Do you plan to synchronise?
Regards
