### ISSUE TITLE
Multiple cross-references in the ReadME

### ISSUE THREAD

**Issue by DonaldTsang** [wooorm/franc#79]
Please include these repos in the ReadME
- https://github.com/dachev/node-cld (C++, 160 languages)
- https://github.com/patrickschur/language-detection (PHP, 110 languages)
- https://github.com/richtr/guessLanguage.js (JS, 100 languages)
- https://github.com/jonathansp/guess-language (Golang, 94 languages) 
- https://github.com/feedbackmine/language_detector (Ruby, 90+ languages)
- https://github.com/optimaize/language-detector (Java, 71 languages)
- https://github.com/endeveit/guesslanguage (Golang, 67 languages)
- https://github.com/dsc/guess-language (Python, 64 languages) 
- https://github.com/Mimino666/langdetect (Python, 55 languages)
- https://github.com/pemistahl/lingua (Kotlin, 55 languages)
- https://github.com/shuyo/language-detection (Java, 53 languages)
- https://github.com/FGRibreau/node-language-detect (JS, 52 languages)
- https://github.com/Ousret/charset_normalizer (Python, 50 languages)

**Comment by DonaldTsang** [comment]
https://github.com/Ousret/charset_normalizer/issues/26

**Comment by wooorm** [comment]
Hi Donald! I don’t think every project should maintain a list of alternatives.
You could create an [awesome list](https://github.com/sindresorhus/awesome) though, or maybe those already exist?
