### ISSUE TITLE
Typescript error? with only

### ISSUE THREAD

**Issue by yoo-gyoon** [wooorm/franc#80]
Hi,

Thank you for providing this wonderful package.

I am using `franc` in Node 10 with TypeScript.

When using `only`, as shown in your documentation:
`console.log(franc.all('O Brasil caiu 26 posições', {only: ['por', 'spa']}))`

I am getting the following TypeScript error.

> Argument of type '{ only: string[]; }' is not assignable to parameter of type 'Options'.
  Object literal may only specify known properties, and 'only' does not exist in type 'Options'.ts(2345)

Is this an outstanding issue or have a been doing something wrong?
I just started using TypeScript, and will look further into this issue (maybe even try a PR!).

Thank you 😊

**Comment by wooorm** [comment]
Hi there!

You are doing it right. The types aren’t correct. However, franc itself doesn’t provide typescript types. It’s probably a bug where the userland-provided types don’t match the implementation https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/franc/index.d.ts

**Comment by yoo-gyoon** [comment]
Thank you.

adding `only?: Array<string>;` to the type definition sorts this out.
I will send a PR to the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repo.

I have another issue/question and will open another Issue thread.

Thank you 😊
