### ISSUE TITLE
Wrong detection

### ISSUE THREAD

**Issue by MadGhigno** [wooorm/franc#81]
With text "Change in Boardroom" returns

[
    [
        "nld",
        1
    ],
    [
        "afr",
        0.9468399291199054
    ],
    [
        "tiv",
        0.9155345540460721
    ],
    [
        "uig",
        0.8795038393384524
    ],
    [
        "dan",
        0.7601890135853515
    ],
....

I have many other examples where detection is wrong if you need them for debug.

bye
_MadGhigno_

**Comment by wooorm** [comment]
See https://github.com/wooorm/franc#whats-not-so-cool-about-franc and other closed issues
