### ISSUE TITLE
franc.all returning [ 'und', 1 ] for a language contained in the main franc package

### ISSUE THREAD

**Issue by gyoon-dev** [wooorm/franc#82]
The [main franc package](https://github.com/wooorm/franc/tree/master/packages/franc) is documented to contain 187 languages, including [Korean](https://iso639-3.sil.org/code/kor).

However when using the following code: 

`franc.all(${someString}, {only: ['kor']})`

the result in the console reads
> [ 'und', 1 ]

while eng shows a reasonable / expected result.

`franc.all(${someString}, {only: ['eng']})`
>  [ [ 'eng', 1 ] ]

Is Korean contained in a different franc package other than the main package?

Thank you.

**Comment by wooorm** [comment]
Could you provide the actual code you use to get these results? So I can try and reproduce this?

**Comment by wooorm** [comment]
@yoo-gyoon Ping!
