### ISSUE TITLE
Use semver

### ISSUE THREAD

**Issue by xamgore** [wooorm/franc#87]
Hi! Thanks for such a great package! Did you know about [semver](https://semver.org/)? Maybe you could just bump the minor version when there are no breaking changes?

**Comment by wooorm** [comment]
Yes, this project adheres to semver.

**Comment by xamgore** [comment]
But [there are no](https://github.com/wooorm/franc/releases) breaking changes, are there?

**Comment by wooorm** [comment]
Yes there are, [a couple were caught by the tests](https://github.com/wooorm/franc/commit/012bf5024590513d6673bd336f065ec7070f1dc6#diff-583d616f4b01bf1fa153e71c0cef7de7).
