### ISSUE TITLE
Language detection error!

### ISSUE THREAD

**Issue by tailot** [wooorm/franc#91]
```
#!/usr/bin/env node

var franc = require("franc");

var t = franc('Hola! Cómo estás ?') 

console.log(t) // "epo"
```

The "epo" output appears to be incorrect.

**Comment by wooorm** [comment]
See https://github.com/wooorm/franc#whats-not-so-cool-about-franc and other closed issues!

**Comment by tailot** [comment]
Obviously 10 characters (https://github.com/wooorm/franc/blob/72af9347b1394b54648b50f3935b0c283b7f38a9/packages/franc/index.js#L24) of limit are not enough as default.
Fortunately in production I will pass long texts. Thank you.

**Comment by wooorm** [comment]
Maybe! Thought about that too, however, that throws an exception, and the fact that it doesn’t work well on small sets is basically at the top of the docs! 🤷‍♂️
