### ISSUE TITLE
Adding a language

### ISSUE THREAD

**Issue by Mejans** [wooorm/franc#95]
Hello,
How can I help adding Occitan language?
Wikipedia already hosts the UDHR here: https://oc.wikipedia.org/wiki/Declaracion_Universala_dels_Dreches_Umans

Best regards

**Comment by wooorm** [comment]
Sounds like a great idea, but this project is taking data from other places that first need to support it. See some of the closed issues for more: https://github.com/wooorm/franc/issues?q=add+language

**Comment by Mejans** [comment]
I wrote to http://unicode.org/udhr/contributing.html yesterday,
we will see

**Comment by wooorm** [comment]
That's awesome!
